MAX_NODE=4
MIN_NODE=2
SCALEUP_THRESHOLD=60
SCALEDOWN_THRESHOLD=40
CLUSTER_ID='autoscale'
AWS_ACCESS_KEY='AKIXXXXXXXXXXXXXXXXX'
AWS_SECRET_KEY='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
REGION='us-east-1'
